repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: "v5.0.0"
    hooks:
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-yaml
      - id: check-toml
      - id: check-json

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.11.13"
    hooks:
      - id: ruff-check
        args: [--fix --config=pyproject.toml]
      - id: ruff-format
        args: [--config=pyproject.toml]
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
        args:
          - --extra-keys
          - >
            metadata.language_info.version
            metadata.language_info.codemirror_mode
            metadata.language_info.nbconvert_exporter
            metadata.language_info.pygments_lexer
            metadata.language_info.file_extension
            metadata.widgets